### ISSUE TITLE
JOI converting date wrongly

### ISSUE THREAD

**Issue by UmerIftikhar** [hapijs/joi-date-extensions#10]
I am simply trying to validate the input format, which is done correctly by joi.  
However my input date is decremented by one day by joi-date-extension.

* *node*:  8.10.0
* *joi*: 13.0.0
* *joi-date-extension* : 1.2.0

```js
import BaseJoi from 'joi';
import Extension from 'joi-date-extensions';
const Joi = BaseJoi.extend(Extension);
const schema = Joi.any();

myDate: Joi.date().format('YYYY-MM-DD')
```
#### INPUT:    
2018-02-18

#### RESULT:   
2018-04-17T00:00:00.000Z

#### EXPECTED OUTPUT:  
2018-04-18T00:00:00.000Z

**Comment by Marsup** [comment]
Sorry, can't reproduce. Have you tried with the new `utc()` ?

**Comment by UmerIftikhar** [comment]
`utc()` function solved the issue.
