### ISSUE TITLE
Issue with optional date

### ISSUE THREAD

**Issue by bnadim** [hapijs/joi-date-extensions#2]
#### Context

* *node version*: 6.9.1
* *joi version*: 10.0.1 - extension 1.0.0
* *environment* (node, browser): node
* *used with* (hapi, standalone, ...): standalone
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce ?

Fields with format option become required even if they are written as optional

```js
const BaseJoi = require('joi')
const Extension = require('joi-date-extensions')
const Joi = BaseJoi.extend(Extension)

const schema = Joi.object().required().keys({
    date: Joi.date().format('YYYY-MM-DD').optional()
});

const data = { }

Joi.validate(data, schema, { allowUnknown: true }, (err, validatedData) => {
    if (err) {
        console.log('Validation error : ', err)
    } else {
        console.log('Validation success')
    }
})
```

#### Which result you had ?
'"date" must be a string with one of the following formats YYYY-MM-DD'

#### What did you expect ?
Data should be a valid result

**Comment by Marsup** [comment]
Thanks for the report, patch published.
