### ISSUE TITLE
Replacing default error message (validation error message)

### ISSUE THREAD

**Issue by alonp99** [hapijs/joi-date-extensions#4]
#### Context

* *node version*: 8.3
* *joi version*: 10.0.6
* *environment* (node, browser): chrome
* *used with* (hapi, standalone, ...): joi-full
* *any other relevant information*: 

#### What are you trying to achieve or the steps to reproduce ?

Trying to replace error message ('must be a string with one of the following formats {{format}}')
```javascript
 language: {
      format: ' new message',  // not working
      date: {
        format: 'new message, // not working
     },
```
#### Which result you had ?
the original error message stays
#### What did you expect ?
new message to appear

**Comment by Marsup** [comment]
Can you show some code to understand exactly what you're doing ? It works for me.
https://runkit.com/embed/54z3j7euj97j
