### ISSUE TITLE
Strict validation

### ISSUE THREAD

**Issue by rightaway** [hapijs/joi-date-extensions#6]
As suggested in https://github.com/hapijs/joi/issues/1396#issuecomment-357792636, could joi-date-extensions be made to offer strict validation instead of changing the dates? `moment` is already a dependency and has a function to do this.

**Comment by Marsup** [comment]
Sure, why not. I'd accept a PR to fix that.

**Comment by Marsup** [comment]
As pointed out by #11, it's already the case.
